config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, :categories, except: [:edit, :update, :show]
  end

  get 'about' => 'about#show'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  def index
    @category = Category.all.order(id: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    # ActiveModel::ForbiddenAttributesError < StandardError
    #https://api.rubyonrails.org/classes/ActiveModel/ForbiddenAttributesError.html
    params.permit!
    @category = Category.new(params[:category])

    if @category.save
      redirect_to [:admin, :categories], notice: 'Category created!'
    else
      render :new
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :authorize

  def show
    @category = Category.find(params[:id])
    # raise @category.inspect
    @products = @category.products.order(created_at: :desc)
  end

end

app/views/admin/categories/index.html.erb
<section class="admin-products-index">

  <header class="page-header">
    <h1>Admin &raquo; Category</h1>
  </header>

  <div class="well">
    <%= link_to '+ New Category', new_admin_category_path, class: 'btn btn-info' %>
  </div>

  <div class="panel panel-default products">

    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Category</th>
        </tr>

      </thead>
      <tbody>
        <% @category.each do |item| %>
          <tr>
            <td><%= item.name %></td>
          <tr>  
        <% end %>
      </tbody>
    </table>

  </div>

</section>

app/views/admin/categories/new.html.erb
<section class="admin-products-new">

  <header class="page-header">
    <h1>Admin &raquo; New Category</h1>
  </header>

  <div class="well">
    <%= link_to 'All Category', new_admin_category_path, class: 'btn btn-info' %>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <%= form_for [:admin, @category] do |form| %>

        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>


        <%= form.submit 'Create Category', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</section>